# Generated by Django 5.1.7 on 2025-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="school_description",
            field=models.TextField(default="My Unique Orginization!"),
        ),
        migrations.AlterField(
            model_name="school",
            name="school_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
