# Generated by Django 5.1.7 on 2025-03-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_customuser_credit_alter_customuser_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
