# Generated by Django 5.1.7 on 2025-03-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0003_remove_customuser_role_schoolmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolmembership",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="schoolmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                    ("chef", "Chef"),
                ],
                default="student",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="schoolmembership",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_auth.school"
            ),
        ),
        migrations.AlterField(
            model_name="schoolmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
