# Generated by Django 5.1.7 on 2025-03-30 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0005_customuser_role_delete_schoolmembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_schools",
                to="custom_auth.school",
            ),
        ),
    ]
