# Generated by Django 5.1.7 on 2025-03-30 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0007_school_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="schools", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
