# Generated by Django 5.1.7 on 2025-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0008_alter_school_users"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="orders",
            field=models.ManyToManyField(
                blank=True, related_name="schools", to="order.order"
            ),
        ),
    ]
