# Generated by Django 5.1.7 on 2025-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="food_choice",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="order",
            name="school",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="FoodChoice",
        ),
        migrations.AddField(
            model_name="order",
            name="food_choice",
            field=models.TextField(default="Give me something random!"),
        ),
    ]
