# Generated by Django 5.1.7 on 2025-03-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0009_school_orders"),
        ("order", "0002_remove_order_food_choice_remove_order_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_auth.school"
            ),
        ),
    ]
